vich_uploader:
    db_driver: orm

    mappings:
        aliment_images:
            uri_prefix: /images/aliments
            upload_destination: '%kernel.project_dir%/public/images/aliments'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer


        categories_images:
            uri_prefix: /images/categories
            upload_destination: '%kernel.project_dir%/public/images/categories'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer